version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building Spring Boot app..."
      - mvn clean package -DskipTests
      - cp target/AWS-Deploy.jar application.jar
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - zip AWS-Deploy.zip application.jar

artifacts:
  files:
    - AWS-Deploy.zip
