version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building Spring Boot App..."
      - mvn clean package -DskipTests
      - mkdir -p build
      - cp target/AWS-Deploy.jar build/application.jar
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r AWS-Deploy.zip build/

artifacts:
  files:
    - AWS-Deploy.zip
