version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo "Java version:"
      - java -version
      - echo "Cleaning previous builds..."
      - mvn clean
  build:
    commands:
      - echo "Building the Spring Boot JAR..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - target/AWS-Deploy.jar
  discard-paths: yes
