version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - target/AWS_Deploy-0.0.1-SNAPSHOT.jar
  discard-paths: yes
